      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add playlist.m3u epg.xml
          git commit -m "Update list and EPG" || exit 0
          git push
